FACEBOOK_USERNAME_PATTERN = "^[a-zA-Z0-9.]+$"
FACEBOOK_USERNAME_MIN_LENGTH = 5
FACEBOOK_USERNAME_MAX_LENGTH = 50
FACEBOOK_PASSWORD_MIN_LENGTH = 8
USERNAME_PATTERN_MISMATCH_ERROR = "Username doesn't seems to be valid based on the pattern"
USERNAME_LENGTH_MISMATCH_ERROR = "Length of username should be between 5-50"
PASSWORD_LENGTH_MISMATCH_ERROR = "Length of password should not be less than 8"
FACEBOOK_BASE_URL = "https://m.facebook.com/"
FACEBOOK_BASE_URL_WITHOUT_SLASH = "https://m.facebook.com"
FACEBOOK_BASE_URL_WEB = "https://www.facebook.com/"
OTEHR_FACEBOOK_BASE_URL = FACEBOOK_BASE_URL + "profile.php?id="
FACEBOOK_LOGIN_URL = FACEBOOK_BASE_URL + "login"
FACEBOOK_ABOUT_URL = FACEBOOK_BASE_URL + "{0}/about"
OTEHR_FACEBOOK_ABOUT_URL = OTEHR_FACEBOOK_BASE_URL + "{0}?v=info"
FACEBOOK_FRIENDS_URL = FACEBOOK_BASE_URL + "{0}/friends"
OTEHR_FACEBOOK_FRIENDS_URL = OTEHR_FACEBOOK_BASE_URL + "{0}&v=friends"
PICKEL_FILENAME = "ObjectData.pkl"